### ISSUE TITLE
CDM flowChart

### ISSUE THREAD

**Issue by kimkangho** [jsong00505/CDM#2]
CDM FlowChart Detail

https://drive.google.com/file/d/0B73lu4uD8AsvRFBrb3dYcVItVEk/view?usp=sharing

- [x] 1. Main flow (Customer, CS, Developer)

- [x] 2. e-mail flow
- [x]  2-1. SMTP
- [x]  2-2. IMAP (IMAP to Board)

- [x] 3. CS flow 
- [x]  3-1. FAQ
- [x]  3-2. Sample file

- [x] 4. Board flow (Kanban)
- [x]  4-1. Making card
- [x]  4-2. Employee Selection

- [x] 5. Chatting flow
- [x]  5-1. Action push

- [x] 6. Inbound call flow

**Comment by kimkangho** [comment]
https://www.draw.io/?chrome=0&lightbox=1&edit=https%3A%2F%2Fwww.draw.io%2F%23G0B73lu4uD8AsvRFBrb3dYcVItVEk&nav=1#G0B73lu4uD8AsvRFBrb3dYcVItVEk

**Comment by kimkangho** [comment]
2-2 IMAP to Board is done.

**Comment by jsong00505** [comment]
The link doesn't work. Please check it for me :(

**Comment by kimkangho** [comment]
New link is here. Check is out! 
https://drive.google.com/file/d/0B73lu4uD8AsvRFBrb3dYcVItVEk/view?usp=sharing

**Comment by kimkangho** [comment]
4-1. Making card
4-2. Employee Selection
6. Inbound call flow is done.

**Comment by kimkangho** [comment]
2-1. SMTP is done.

**Comment by kimkangho** [comment]
3-1. FAQ
5. Chatting flow
5-1. Action push

**Comment by jsong00505** [comment]
I don't know there are another best way to convert a pdf file from yo link.
[CDM Process Flow.pdf](https://github.com/jsong00505/CDM/files/636568/CDM.Process.Flow.pdf)
